#!/usr/bin/env python3
"""
Widoco HTML Documentation Modifier
This script post-processes Widoco-generated HTML documentation to:
- Move namespace declarations to the end as independent section
- Move WebVOWL iframe after introduction
- Delete specific sections
- Reorganize overview boxes in cross-reference sections
- Move Overview section to the end
"""

from pathlib import Path
from bs4 import BeautifulSoup
import re

# ============================================================
# CONFIGURATION SECTION
# ============================================================

# Target HTML file (generated by Widoco)
HTML_FILE = "doc/main_doc/index-en.html"

# Backup original file
CREATE_BACKUP = True


# ============================================================
# END OF CONFIGURATION SECTION
# ============================================================


class WidocoModifier:
    """Modify Widoco-generated HTML documentation."""

    def __init__(self, html_file):
        self.html_file = Path(html_file)
        self.backup_file = self.html_file.with_suffix('.html.backup')
        self.soup = None

    def load_html(self):
        """Load the HTML file."""
        print(f"Loading HTML file: {self.html_file}")

        if not self.html_file.exists():
            print(f"✗ Error: HTML file not found: {self.html_file}")
            return False

        try:
            with open(self.html_file, 'r', encoding='utf-8') as f:
                self.soup = BeautifulSoup(f.read(), 'html.parser')
            print("✓ HTML file loaded successfully")
            return True
        except Exception as e:
            print(f"✗ Error loading HTML: {e}")
            return False

    def create_backup(self):
        """Create a backup of the original HTML file."""
        if not CREATE_BACKUP:
            return True

        print(f"Creating backup: {self.backup_file}")
        try:
            import shutil
            shutil.copy2(self.html_file, self.backup_file)
            print("✓ Backup created successfully")
            return True
        except Exception as e:
            print(f"✗ Error creating backup: {e}")
            return False

    def find_section(self, identifier):
        """Find a section by ID or heading text."""
        # Try finding by ID
        section = self.soup.find(id=identifier)
        if section:
            return section

        # Try finding by heading text (case-insensitive, partial match)
        for heading in self.soup.find_all(['h1', 'h2', 'h3', 'h4']):
            heading_text = heading.get_text().strip().lower()
            if identifier.lower() in heading_text:
                # Return the parent section/div or the heading itself
                parent = heading.find_parent(['div', 'section'])
                return parent if parent else heading

        return None

    def find_all_sections(self, identifier):
        """Find all sections matching an identifier."""
        sections = []

        # Find by ID
        section = self.soup.find(id=identifier)
        if section:
            sections.append(section)

        # Find by heading text
        for heading in self.soup.find_all(['h1', 'h2', 'h3', 'h4']):
            heading_text = heading.get_text().strip().lower()
            if identifier.lower() in heading_text:
                parent = heading.find_parent(['div', 'section'])
                section_to_add = parent if parent else heading
                if section_to_add not in sections:
                    sections.append(section_to_add)

        return sections

    def make_namespace_independent_section(self):
        """
        Make namespace declarations an independent section (not subsection of acknowledgements).
        Also moves it to the end of the document.
        """
        print("\nMaking namespace declarations an independent section and moving to end...")

        # Find namespace declarations
        namespace_identifiers = [
            'namespacedeclarations',
            'ns-declarations',
            'namespace-declarations',
            'namespace declarations'
        ]

        namespace_section = None
        for identifier in namespace_identifiers:
            namespace_section = self.find_section(identifier)
            if namespace_section:
                break

        if not namespace_section:
            print("  ⚠ Namespace declarations section not found")
            return False

        # Find or create the heading for namespace section
        namespace_heading = namespace_section.find(['h2', 'h3', 'h4'])

        # If it's currently h3 or h4 (subsection), change it to h2
        if namespace_heading and namespace_heading.name in ['h3', 'h4']:
            new_heading = self.soup.new_tag('h2')
            new_heading.string = namespace_heading.get_text()
            # Copy any attributes
            for attr, value in namespace_heading.attrs.items():
                new_heading[attr] = value
            namespace_heading.replace_with(new_heading)
            print("  ✓ Changed namespace heading from subsection to main section (h2)")

        # Move to end of document (before any script tags at the end)
        body = self.soup.find('body')
        if body:
            namespace_section.extract()
            # Insert before script tags if they exist at the end
            scripts = body.find_all('script', recursive=False)
            if scripts:
                scripts[-1].insert_before(namespace_section)
            else:
                body.append(namespace_section)
            print("✓ Namespace declarations moved to end as independent section")
            return True
        else:
            print("  ⚠ Could not find body element")
            return False

    def move_webvowl_after_introduction(self):
        """Move WebVOWL iframe directly after the introduction section."""
        print("\nMoving WebVOWL iframe after introduction...")

        # Find WebVOWL iframe or container
        webvowl_element = None

        # Try finding iframe
        iframes = self.soup.find_all('iframe')
        for iframe in iframes:
            src = iframe.get('src', '')
            if 'webvowl' in src.lower():
                webvowl_element = iframe.find_parent(['div', 'section']) or iframe
                break

        # Try finding WebVOWL container div
        if not webvowl_element:
            for div in self.soup.find_all('div'):
                div_id = div.get('id', '')
                if 'webvowl' in div_id.lower():
                    webvowl_element = div
                    break

        if not webvowl_element:
            print("  ⚠ WebVOWL iframe not found")
            return False

        # Find introduction section
        intro_identifiers = ['introduction', 'intro', 'abstract']
        intro_section = None

        for identifier in intro_identifiers:
            intro_section = self.find_section(identifier)
            if intro_section:
                break

        if not intro_section:
            print("  ⚠ Introduction section not found")
            return False

        # Move WebVOWL after introduction
        webvowl_element.extract()
        intro_section.insert_after(webvowl_element)
        print("✓ WebVOWL iframe moved after introduction")
        return True

    def delete_overview_after_iframe(self):
        """Delete the overview section that appears after the iframe."""
        print("\nDeleting overview section after iframe position...")

        # Find all overview sections
        overview_sections = self.find_all_sections('overview')

        if not overview_sections:
            print("  ⚠ No overview sections found")
            return False

        # Find the iframe to use as reference
        webvowl_iframe = None
        iframes = self.soup.find_all('iframe')
        for iframe in iframes:
            if 'webvowl' in iframe.get('src', '').lower():
                webvowl_iframe = iframe
                break

        deleted = False
        for overview in overview_sections:
            # Check if this overview comes before any cross-reference section
            # (the one we want to keep comes later in the document)
            next_siblings = []
            current = overview
            while current:
                current = current.find_next_sibling()
                if current:
                    next_siblings.append(current)

            # Check if there's a cross-reference section after this overview
            has_crossref_after = False
            for sibling in next_siblings:
                if sibling.find(string=re.compile(r'cross.?reference', re.IGNORECASE)):
                    has_crossref_after = True
                    break

            # If this overview is early in the document (has cross-ref after it), delete it
            if has_crossref_after:
                overview.decompose()
                print("  ✓ Deleted early overview section")
                deleted = True
                break

        if not deleted:
            print("  ⚠ Could not identify overview section to delete")

        return deleted

    def delete_references_section(self):
        """Delete the references section."""
        print("\nDeleting references section...")

        references_identifiers = ['references', 'reference']

        for identifier in references_identifiers:
            sections = self.find_all_sections(identifier)
            for section in sections:
                # Make sure it's actually a references section, not just containing the word
                heading = section.find(['h1', 'h2', 'h3', 'h4'])
                if heading:
                    heading_text = heading.get_text().strip().lower()
                    if heading_text == 'references' or heading_text == 'reference':
                        section.decompose()
                        print("  ✓ Deleted references section")
                        return True

        print("  ⚠ References section not found")
        return False

    def move_overview_boxes_in_crossref(self):
        """
        Move the overview boxes (with lists of instances/properties) to the end
        of their respective subsections in the Cross Reference section.
        """
        print("\nMoving overview boxes to end of cross-reference subsections...")

        # Find the cross-reference section
        crossref_section = self.find_section('cross-reference') or self.find_section('crossreference')

        if not crossref_section:
            print("  ⚠ Cross-reference section not found")
            return False

        moved_count = 0

        # Find all subsections (h3 or h4 within cross-reference)
        subsections = crossref_section.find_all(['h3', 'h4'])

        for subsection_heading in subsections:
            # Find the overview box in this subsection
            # Widoco typically uses divs with class containing "entity" or id containing "overview"
            current = subsection_heading
            overview_box = None
            subsection_content = []

            # Collect content until next subsection heading
            while current:
                current = current.find_next_sibling()
                if current and current.name in ['h3', 'h4', 'h2']:
                    break
                if current:
                    subsection_content.append(current)
                    # Look for overview box (usually a div with ul/ol)
                    if current.name == 'div' and current.find(['ul', 'ol']):
                        # Check if it looks like an overview box
                        list_items = current.find_all('li')
                        if len(list_items) > 0 and any('http' in str(li) for li in list_items):
                            overview_box = current

            # If we found an overview box and it's not already at the end
            if overview_box and subsection_content and overview_box != subsection_content[-1]:
                # Move to end of subsection content
                overview_box.extract()
                last_element = subsection_content[-1]
                last_element.insert_after(overview_box)
                moved_count += 1
                print(f"  ✓ Moved overview box in: {subsection_heading.get_text().strip()}")

        if moved_count > 0:
            print(f"✓ Moved {moved_count} overview box(es)")
        else:
            print("  ⚠ No overview boxes found to move")

        return moved_count > 0

    def move_overview_section_to_end(self):
        """Move the Overview section to the end of the document (before namespace)."""
        print("\nMoving Overview section to end of document...")

        # Find all overview sections
        overview_sections = self.find_all_sections('overview')

        if not overview_sections:
            print("  ⚠ Overview section not found")
            return False

        # We want to move the main overview section (likely the last one, after cross-ref)
        # Find which one comes after cross-reference section
        crossref_section = self.find_section('cross-reference') or self.find_section('crossreference')

        overview_to_move = None

        if crossref_section:
            # Find overview that comes after cross-reference
            for overview in overview_sections:
                if crossref_section.sourceline and overview.sourceline:
                    if overview.sourceline > crossref_section.sourceline:
                        overview_to_move = overview
                        break
                else:
                    # Fallback: check position in document
                    all_elements = list(self.soup.find_all(['div', 'section']))
                    try:
                        crossref_idx = all_elements.index(crossref_section)
                        overview_idx = all_elements.index(overview)
                        if overview_idx > crossref_idx:
                            overview_to_move = overview
                            break
                    except ValueError:
                        continue

        # If we couldn't determine which one, use the last one
        if not overview_to_move and overview_sections:
            overview_to_move = overview_sections[-1]

        if not overview_to_move:
            print("  ⚠ Could not identify Overview section to move")
            return False

        # Move to end (before namespace declarations)
        body = self.soup.find('body')
        if body:
            overview_to_move.extract()

            # Try to insert before namespace declarations
            namespace_section = self.find_section('namespace declarations')
            if namespace_section:
                namespace_section.insert_before(overview_to_move)
            else:
                # Otherwise just append to body (before scripts)
                scripts = body.find_all('script', recursive=False)
                if scripts:
                    scripts[-1].insert_before(overview_to_move)
                else:
                    body.append(overview_to_move)

            print("✓ Overview section moved to end")
            return True
        else:
            print("  ⚠ Could not find body element")
            return False

    def save_html(self):
        """Save the modified HTML file."""
        print("\nSaving modified HTML...")

        try:
            with open(self.html_file, 'w', encoding='utf-8') as f:
                f.write(str(self.soup.prettify()))
            print(f"✓ Modified HTML saved: {self.html_file}")
            return True
        except Exception as e:
            print(f"✗ Error saving HTML: {e}")
            return False

    def run(self):
        """Execute the complete modification process."""
        print("=" * 60)
        print("Widoco HTML Documentation Modifier")
        print("=" * 60)

        # Step 1: Load HTML
        if not self.load_html():
            return False

        # Step 2: Create backup
        if not self.create_backup():
            print("Warning: Could not create backup, continuing anyway...")

        # Step 3: Move WebVOWL iframe after introduction
        self.move_webvowl_after_introduction()

        # Step 4: Delete the overview section after iframe
        self.delete_overview_after_iframe()

        # Step 5: Delete references section
        self.delete_references_section()

        # Step 6: Move overview boxes in cross-reference sections
        self.move_overview_boxes_in_crossref()

        # Step 7: Move Overview section to end
        self.move_overview_section_to_end()

        # Step 8: Make namespace declarations independent and move to end
        self.make_namespace_independent_section()

        # Step 9: Save
        if not self.save_html():
            return False

        print("\n" + "=" * 60)
        print("Modification completed successfully!")
        print("=" * 60)
        if CREATE_BACKUP:
            print(f"Original backup: {self.backup_file}")
        print(f"Modified file: {self.html_file}")
        print("=" * 60)

        return True


def main():
    """Main function to run the modifier."""
    modifier = WidocoModifier(HTML_FILE)
    modifier.run()


if __name__ == "__main__":
    main()
